api_endpoint: "http://localhost:8585/api"
ingest_bot_token: "eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZyIsInN1YiI6ImluZ2VzdGlvbi1ib3QiLCJyb2xlcyI6WyJJbmdlc3Rpb25Cb3RSb2xlIl0sImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVuLW1ldGFkYXRhLm9yZyIsImlzQm90Ijp0cnVlLCJ0b2tlblR5cGUiOiJCT1QiLCJpYXQiOjE3Mjk4MzY1MTMsImV4cCI6bnVsbH0.wjbnVtxV06Eqql9cUcPaRWhVCGWri6Bz_VtZTJnLI7n3Y7iP6NK_WGbrt6rhz2paZ6zIm-dXfNNb4ioSty0X1qNvvR9Ro9_RHGXUUKRPJ_Md3Rhs9gi841hptw6nem2dPdO5l7CaQJYmFlLwj_jfRWhX820jLkgEJFL7AxcdfV__0hlS4TNCFP2gOY3ArHcPpX_GrPeyF0zpasGuXIMhJF8xsbfRoYKrMkgrO2URFFF54wyWBVHL1dF1Bi8C0x7mT1omhI-js2j52J7xwb2s_H0RTblp-ZCY8Lr41zhd3W9vZWT_84-cxwmaXW0cQYFgewVKBMQUcyRYtojZiLZEbw"
mssql_connection_detail:
  hostPort: "host.docker.internal:1433"
  username: "openmetadata_login"
  password: "sql123"
  database: "SetDB"

